-include .env

deploy:; forge script script/DeployLightPad.s.sol:DeployLightPad --rpc-url $(PEGASUS_RPC_URL) --private-key $(PRIVATE_KEY) --broadcast --verify --etherscan-api-key $(BLOCKSCOUT_API_KEY) -vvvv